name: deploy test-app

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - id: get-sha
        run: |
          echo ::set-output name=sha::$( curl -u "u:${{secrets.ACCESS_TOKEN}}" https://api.github.com/repos/${{env.REPOSITORY}}/git/ref/heads/${{ github.event.inputs.branch }} | jq .object.sha | tr -d '"' )

      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker build
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository_owner }}/test-app:latest
            ghcr.io/${{ github.repository_owner }}/test-app:${{ steps.get-sha.outputs.sha }}


